// automatically generated by the FlatBuffers compiler, do not modify

package csce315.group29.models;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class ActorNeighborCount extends Table {
  public static ActorNeighborCount getRootAsActorNeighborCount(ByteBuffer _bb) { return getRootAsActorNeighborCount(_bb, new ActorNeighborCount()); }
  public static ActorNeighborCount getRootAsActorNeighborCount(ByteBuffer _bb, ActorNeighborCount obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public ActorNeighborCount __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String nconst() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nconstAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer nconstInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public int count() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createActorNeighborCount(FlatBufferBuilder builder,
      int nconstOffset,
      int count) {
    builder.startObject(2);
    ActorNeighborCount.addCount(builder, count);
    ActorNeighborCount.addNconst(builder, nconstOffset);
    return ActorNeighborCount.endActorNeighborCount(builder);
  }

  public static void startActorNeighborCount(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addNconst(FlatBufferBuilder builder, int nconstOffset) { builder.addOffset(0, nconstOffset, 0); }
  public static void addCount(FlatBufferBuilder builder, int count) { builder.addInt(1, count, 0); }
  public static int endActorNeighborCount(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

